name: Chest
version: "${project.version}"
description: Allows you to have virtual private chests. Based on AlphaChest, and is modified for Betterverse.
authors: [Betterverse, 4am, Mast3rPlan]
website: http://www.betterverse.net

main: net.betterverse.chest.ChestPlugin
depend: [Spout]

commands:
    chest:
        description: Opens a virtual player-specific chest.
        usage: |
            /<command> - Opens your private chest.
            /<command> [player] - Opens someone else's chest.
        permission: ac.chest
    clearchest:
        description: Clears the contents of a chest.
        usage: |
            /<command> - Clears your private chest.
            /<command> [player] - Clears someone else's chest.
        permission: ac.chest
    savechests:
        description: Saves the chests to disk.
        usage: |
            /<command> - Saves all chests to disk.
        permission: ac.save
    workbench:
        aliases: [craft, craftbox, craftingbox]
        description: Opens a virtual workbench.
        permission: ac.workbench
